# Generated by Django 3.1.3 on 2021-01-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
