# Generated by Django 3.1.3 on 2020-12-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='', path='static/img'),
        ),
    ]
