# Generated by Django 3.1.3 on 2021-01-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_auto_20210110_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_present',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
