# Generated by Django 3.1.3 on 2021-01-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_auto_20210110_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='is_present',
            field=models.NullBooleanField(),
        ),
    ]
