# Generated by Django 3.1.3 on 2021-01-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0010_auto_20210110_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=500)),
                ('summary', models.CharField(max_length=5000)),
                ('image', models.FilePathField(default='', path='E:\\Python_workspace\\Portfolio-website-using-django\\myportfolio/static/img')),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fb_link', models.URLField()),
                ('github_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('linkedin_link', models.URLField()),
            ],
        ),
    ]
